# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f python/app/requirements.txt ]; then pip install -r python/app/requirements.txt; fi
    - name: Lint with pylint
      run: |
        # stop the build if pylint is 10 for everything
        pylint python/app
    - name: Lint with mypy
      run: |
        # stop the build if pylint is 10 for everything
        mypy python/app
    - name: Unit Test with pytest
      run: |
        pytest python/app/test
    - name: Build the stack
      run: docker-compose up -d
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_DB: ${{ secrets.POSTGRES_PASSWORD }}
    - name: Intergration Test with pytest
        run: |
          pytest python/app/test



